edition: 1.0.0          #  命令行YAML规范版本，遵循语义化版本（Semantic Versioning）规范
name: website-hexo-container       #  项目名称
access: '{{ access }}'  #  秘钥别名

services:
  framework: #  服务名称
    component: fc  # 组件名称
    actions:
      pre-deploy:
        - component: fc build --use-docker --dockerfile ./code/Dockerfile
    props: #  组件的属性值
      region: '{{ region }}'
      service:
        name: '{{ serviceName }}'
        description: "Serverless Devs Website Service"
      function:
        name: '{{ functionName }}'
        description: "Serverless Devs Website hexo Function"
        codeUri: ./code
        memorySize: 512
        runtime: custom-container
        customContainerConfig:
          image: '{{ acrRegistry }}'
        timeout: 30
      triggers:
        - name: httpTrigger
          type: http
          config:
            authType: anonymous
            methods:
              - GET
              - POST
              - PUT
              - DELETE
      customDomains:
        - domainName: auto
          protocol: HTTP
          routeConfigs:
            - path: /*
